<a href="https://colab.research.google.com/github/izabellaradichi/programaria_dados/blob/main/exercicio_licitacoes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import numpy as np
import pandas as pd

In [54]:
from google.colab import drive

In [55]:
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [56]:
licitacoes = pd.read_csv('/content/drive/MyDrive/Curso PrograMaria Dados/licitacoes.csv', encoding='latin1', sep=';')

In [57]:
licitacoes.isnull().sum() # mostra contagem de valores nulos por coluna

Número Licitação                0
Código UG                       0
Nome UG                         0
Código Modalidade Compra        0
Modalidade Compra               0
Número Processo                 0
Objeto                          0
Situação Licitação              0
Código Órgão Superior           0
Nome Órgão Superior             0
Código Órgão                    0
Nome Órgão                      0
UF                              0
Município                       0
Data Resultado Compra           0
Data Abertura               10648
Valor Licitação                 0
dtype: int64

In [58]:
licitacoes['Data Abertura'].unique() # Mostra os dados da coluna Data Abertura (para identificar padrão dos dados)

array(['17/08/2016', nan, '30/11/2018', '29/11/2018', '19/06/2018',
       '03/09/2018', '22/11/2018', '12/12/2018', '06/04/2018',
       '14/12/2018', '09/11/2018', '20/04/2018', '04/12/2018',
       '07/12/2018', '29/10/2018', '13/04/2018', '06/11/2018',
       '18/09/2018', '07/11/2018', '06/12/2018', '05/12/2018',
       '23/11/2018', '09/10/2018', '21/11/2018', '31/12/2018',
       '28/12/2018', '08/11/2018', '13/12/2018', '31/10/2018',
       '14/08/2018', '23/10/2017', '10/12/2018', '16/11/2018',
       '27/12/2018', '13/11/2018', '18/12/2018', '27/11/2018',
       '05/11/2018', '21/09/2018', '19/10/2018', '20/11/2018',
       '14/11/2018', '11/10/2018', '25/06/2018', '16/10/2018',
       '12/11/2018', '25/09/2018', '03/10/2018', '26/12/2018',
       '17/12/2018', '10/10/2018', '19/12/2018', '23/10/2018',
       '20/12/2018', '18/10/2018', '11/12/2018', '26/11/2018',
       '03/12/2018', '19/07/2016', '12/06/2017', '23/08/2018',
       '22/10/2018', '25/07/2018', '19/11/2018', '30/10/2018',
       '04/06/2018', '28/11/2018', '01/11/2018', '27/09/2018',
       '21/12/2018', '12/06/2018', '25/10/2018', '25/04/2018',
       '17/10/2018', '05/09/2018', '28/09/2018', '23/01/2018',
       '09/08/2018', '24/12/2018', '06/09/2018', '06/07/2018',
       '03/05/2018', '23/07/2018', '15/11/2018', '29/01/2018',
       '02/10/2018', '04/10/2018', '24/10/2018', '24/09/2018',
       '16/02/2018', '04/09/2018', '17/05/2018', '10/09/2018',
       '26/10/2018', '01/10/2018', '05/10/2018', '18/06/2018',
       '23/12/2018', '05/06/2018', '31/07/2018', '28/06/2018',
       '08/10/2018', '19/09/2018', '15/10/2018', '21/08/2018',
       '08/11/2017', '24/07/2018', '28/03/2018', '19/07/2018',
       '02/05/2018', '27/08/2018', '17/04/2018', '26/09/2018',
       '22/10/2014', '05/04/2018', '29/08/2018', '26/02/2018',
       '09/05/2018', '01/06/2018', '16/08/2018', '24/05/2018',
       '24/08/2018', '12/09/2018', '15/03/2018', '22/03/2018',
       '31/01/2018', '13/06/2018', '15/08/2018', '11/09/2018',
       '28/08/2018', '08/08/2018', '30/08/2018', '27/06/2018',
       '04/04/2018', '03/08/2018', '24/11/2018', '11/04/2018',
       '10/05/2018', '05/07/2018', '20/08/2018', '16/04/2018',
       '02/08/2018', '29/03/2017', '12/07/2018', '10/08/2018',
       '08/05/2018', '08/12/2018', '30/07/2018', '14/09/2018',
       '23/11/2017', '18/04/2017', '13/09/2018', '08/02/2018',
       '17/09/2018', '20/09/2018', '24/04/2018', '31/08/2018',
       '28/11/2017', '21/03/2018', '21/06/2018', '15/05/2018',
       '13/12/2017', '27/07/2018', '22/08/2018', '23/02/2018',
       '14/06/2017', '07/05/2018', '16/07/2018', '02/11/2018',
       '01/12/2018', '30/10/2017', '14/11/2017', '17/08/2018',
       '09/04/2018', '02/04/2018', '22/06/2018', '17/07/2018',
       '27/03/2018', '10/11/2018', '22/12/2018'], dtype=object)

In [59]:
licitacoes['Data Abertura'] = licitacoes['Data Abertura'].fillna('00/00/0000') # substitui valores nulos por valor ficticio (no mesmo formato identificado acima)

In [60]:
licitacoes.isnull().sum() # mostra contagem de valores nulos por coluna (comprovando que foram substituidos os da coluna Data Abertura)

Número Licitação            0
Código UG                   0
Nome UG                     0
Código Modalidade Compra    0
Modalidade Compra           0
Número Processo             0
Objeto                      0
Situação Licitação          0
Código Órgão Superior       0
Nome Órgão Superior         0
Código Órgão                0
Nome Órgão                  0
UF                          0
Município                   0
Data Resultado Compra       0
Data Abertura               0
Valor Licitação             0
dtype: int64